import {
  BaseEntity,
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn
} from "typeorm";
import { ApiProperty } from '@nestjs/swagger';
import { Dialog } from "../dialog/dialog.entity";

@Entity('messages')
export class Message extends BaseEntity {

  @PrimaryGeneratedColumn('uuid')
  @ApiProperty({
    description: 'The unique identifier of the message',
    example: '5e9f8f8f-8f8f-8f8f-8f8f-8f8f8f8f8f8f',
  })
  id: string;

  @Column()
  @ApiProperty({
    description: 'The message content',
    example: 'Hello world',
  })
  text: string;

  @Column()
  @ApiProperty({
    description: 'Is the message is generated by the bot',
    example: true,
  })
  iaGenerated: boolean;

  @ManyToOne(type => Dialog, dialog => dialog.messages, { onDelete: 'CASCADE' })
  dialog: Dialog;

  @ApiProperty({
    description: 'The created date of the message',
    example: '2020-01-01T00:00:00.000Z',
  })
  @CreateDateColumn({
    type: 'timestamp with time zone',
    name: 'created_at',
  })
  createdAt: Date;

  @ApiProperty({
    description: 'The updated date of the message',
    example: '2020-01-01T00:00:00.000Z',
  })
  @UpdateDateColumn()
  updatedAt: Date;
}






